version: "3.7" #Версия docker-compose

volumes:
  db:

services: #Раздел, в котором будут описаны сервисы. Сервисом может быть клиент, сервер, сервер баз данных...

  &php-apache  url-php-apache: #В docker-compose через &-переменная записываем название контейнера. Название контейнера
    container_name: *php-apache #Используем переменную названия этого контейнера
    hostname: *php-apache #Указываем для того чтоб в дальнейшем в коде или .env вместо динамического ip, указывать статической. Что б не менять везде ip контейнера
    ports:  # Организовуем перенаправление порта контейнера на порт компьютера.
      - ${APACHE_CONTAINER_PORT}:80   # При его использовании применяется следующая конструкция: [порт компьютера]:[порт контейнера]
    restart: always
    volumes: # Определяют, что данные из временной структуры — контейнера будут сохраняться на хост машине.
      - ./public:/var/www/html:rw
      - ./docker/apache/sites-enabled/:/etc/apache2/sites-enabled/:ro
    build: #Задаёт путь к файлу Dockerfile, который нужно использовать для создания образа.
      ./docker/apache
    networks:
      - web

  &db-service url-mysql:
    container_name: *db-service
    hostname: *db-service
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_CONTAINER_PORT}:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: &MYSQL_ROOT_PASS pass5
    volumes:
      - db:/var/lib/mysql
    networks:
      - web

  &pma-service url-phpmyadmin:
    container_name: *pma-service
    hostname: *pma-service
    restart: always
    depends_on:
      - *db-service
    ports:
      - ${PHPMYADMIN_CONTAINER_PORT}:80
    image: phpmyadmin
    environment:
      PMA_HOST: *db-service
      MYSQL_ROOT_PASSWORD: *MYSQL_ROOT_PASS
      UPLOAD_LIMIT: "1G"
    networks:
      - web
networks:
  web: 